### ISSUE TITLE
How to use Haxe code in Haxe program loaded as module?

### ISSUE THREAD

**Issue by flashultra** [MasterEric/hxcpp-interop-testbench#1]
Thank you for your tutorial !  Really nice overview of using externs in Haxe.
I would like to ask what would be the correct way to use extern for the Haxe code ( in Haxe) compile to the same target.
For example , I have a main Haxe program ( compilied in c++) and I want to plug-in another module (written in Haxe and compile to cpp) in the main program ( without to recompile the main program). What would be a possible way  to this  ? Maybe the only way is if compile to cppia or if compile (the module program ) to native library ( dll/so/dylib ) and used in that way

**Comment by EliteMasterEric** [comment]
If using the extern method, you have to compile the C/C++ code (either can be used with any of the methods on this repo) into the executable.

If using the CFFI method, you create a DLL in C++ that you can update independently of the main executable.

Why would you want to write the DLL in Haxe though? Why not just make a Haxelib that uses externs, or write the DLL in C++?

EDIT: Reread your post. I think that to do what you want then CPPIA (or potentially Hscript) is your best option.

**Comment by flashultra** [comment]
Thank you for you advice!  CPIIA might be the way to go for me.
About your question, I want to use modules (written in Haxe) after the main program is compiled,, so for that reason extern would not be a good solution.
Here some examples for what I want to create such modules.
For example, I have a main program that listens for some events ( network events, user input ( keyboard, mouse) etc.) and I want send this signal to all listeners. For that purpose I have a separate haxe program that  listen for events. When that event fire up, that program reads and encrypts the file. Let's say I'm using an insecure algorithm to encrypt the file and want to use  more secure one. For that reason I only want to replace my module and not recompile the main program. 
The other example is  if Ihave a server (in Haxe) which receives commands over a network and I want my modules to be called when a certain network command arrives. When I put new module, I want to compile only the module, not the whole server.

**Comment by EliteMasterEric** [comment]
In your examples, you'd definitely want to use CPPIA then.
